<?php

/**
 * @file
 * Themes and preprocessors for the paragraphs page title module.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Breadcrumb\Breadcrumb;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Language\LanguageInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Url;
use Drupal\group\Entity\Group;
use Drupal\group\Entity\GroupContent;
use Drupal\node\Entity\Node;
use Drupal\path_alias\Entity\PathAlias;
use Drupal\subgroup\MalformedLeafException;

/**
 * Implements hook_theme().
 */
function hr_paragraphs_theme($existing, $type, $theme, $path) {
  return [
    'river' => [
      'template' => 'river',
      'variables' => [
        'service' => NULL,
        'service_url' => NULL,
        'data' => [],
        'total' => [],
        'facets' => [],
        'active_facets' => [],
        'pager' => NULL,
        'group' => NULL,
        'view_all' => NULL,
        'set_name' => NULL,
      ],
    ],
    'hr_paragraphs_rw_list' => [
      'template' => 'hr-paragraphs-rw-list',
      'variables' => [
        'data' => [],
        'total' => [],
        'view_all' => NULL,
      ],
    ],
    'hr_paragraphs_rw_key_figures' => [
      'template' => 'hr-paragraphs-rw-key-figures',
      'variables' => [
        'country_iso' => NULL,
        'country_name' => NULL,
        'data' => [],
        'total' => [],
        'view_all' => NULL,
      ],
    ],
    'upcoming_events' => [
      'template' => 'upcoming-events',
      'variables' => [
        'events' => [],
        'read_more' => NULL,
      ],
    ],
    'hr_paragraphs_rss_feed' => [
      'template' => 'hr-paragraphs-rss-feed',
      'variables' => [
        'items' => [],
        'options' => [],
        'read_more' => NULL,
      ],
    ],
    'hr_paragraphs_iframe' => [
      'template' => 'hr-paragraphs-iframe',
      'variables' => [
        'embed_url' => NULL,
        'width' => NULL,
        'height' => NULL,
        'ratio' => NULL,
      ],
    ],
    'group_children' => [
      'template' => 'group-children',
      'variables' => [
        'children' => [],
      ],
    ],
    'group_nodes' => [
      'template' => 'group-nodes',
      'variables' => [
        'nodes' => [],
      ],
    ],
    'fullcalendar_link' => [
      'template' => 'fullcalendar-link',
      'variables' => [
        'calendar_url' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function hr_paragraphs_group_insert(EntityInterface $entity) {
  if ($entity->bundle() != 'operation') {
    return;
  }

  $langcode = LanguageInterface::LANGCODE_NOT_SPECIFIED;
  $source = '/group/' . $entity->id();

  $path_alias_manager = \Drupal::service('path_alias.manager');
  $group_alias = $path_alias_manager->getAliasByPath($source);

  // Add alias if needed.
  if ($group_alias === $source) {
    $page_title = \Drupal::service('pathauto.alias_cleaner')->cleanString($entity->label());
    $new_alias = '/' . $page_title;

    /** @var \Drupal\pathauto\AliasUniquifier $alias_uniquifier */
    $alias_uniquifier = \Drupal::service('pathauto.alias_uniquifier');
    $alias_uniquifier->uniquify($new_alias, $source, $langcode);

    if ($source !== $new_alias) {
      $path_alias = PathAlias::create([
        'path' => $source,
        'alias' => $new_alias,
      ]);

      $path_alias->save();
    }
  }

  // Add aliases for tabs.
  hr_paragraphs_add_aliases_for_tabs($entity);
}

/**
 * Add Url aliases for all tabs.
 */
function hr_paragraphs_add_aliases_for_tabs(Group $group) {
  $source = '/group/' . $group->id();

  $path_alias_manager = \Drupal::service('path_alias.manager');
  $group_alias = $path_alias_manager->getAliasByPath($source);

  // Add aliases for tabs.
  $tabs = [
    'events',
    'contacts',
    'pages',
    'reports',
    'maps',
    'data',
    'assessments',
  ];

  foreach ($tabs as $tab) {
    $source = '/group/' . $group->id() . '/' . $tab;
    $tab_alias = $group_alias . '/' . $tab;

    $existing_alias = $path_alias_manager->getAliasByPath($source);

    // Skip if an alias is already set.
    if ($existing_alias !== $source) {
      continue;
    }

    if ($source !== $tab_alias) {
      $path_alias = PathAlias::create([
        'path' => $source,
        'alias' => $tab_alias,
      ]);

      $path_alias->save();
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function hr_paragraphs_group_update(EntityInterface $entity) {
  /** @var \Drupal\group\Entity\Group $entity */
  if ($entity->bundle() == 'operation') {
    return hr_paragraphs_group_insert($entity);
  }

  $langcode = LanguageInterface::LANGCODE_NOT_SPECIFIED;
  $source = '/group/' . $entity->id();

  $path_alias_manager = \Drupal::service('path_alias.manager');
  $group_alias = $path_alias_manager->getAliasByPath($source);

  // Add alias if needed.
  if ($group_alias === $source) {
    // Get parent alias.
    if ($entity->hasField('subgroup_tree') && !$entity->subgroup_tree->isEmpty()) {
      $subgroup = $entity;
      $group = Group::load($entity->subgroup_tree->value);

      $path_alias_manager = \Drupal::service('path_alias.manager');

      $group_alias = $path_alias_manager->getAliasByPath('/group/' . $group->id());
      $page_title = \Drupal::service('pathauto.alias_cleaner')->cleanString($entity->label());
      $new_alias = $group_alias . '/' . $page_title;

      $langcode = LanguageInterface::LANGCODE_NOT_SPECIFIED;
      $source = '/group/' . $subgroup->id();

      /** @var \Drupal\pathauto\AliasUniquifier $alias_uniquifier */
      $alias_uniquifier = \Drupal::service('pathauto.alias_uniquifier');
      $alias_uniquifier->uniquify($new_alias, $source, $langcode);

      if ($source !== $new_alias) {
        $path_alias = PathAlias::create([
          'path' => $source,
          'alias' => $new_alias,
        ]);

        $path_alias->save();
      }
    }
  }

  // Add aliases for tabs.
  hr_paragraphs_add_aliases_for_tabs($entity);
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function hr_paragraphs_node_update(EntityInterface $entity) {
  $langcode = LanguageInterface::LANGCODE_NOT_SPECIFIED;
  $source = '/node/' . $entity->id();

  $path_alias_manager = \Drupal::service('path_alias.manager');
  $node_alias = $path_alias_manager->getAliasByPath($source);

  // Skip if an alias is already set.
  if ($node_alias !== $source) {
    return;
  }

  $page_title = \Drupal::service('pathauto.alias_cleaner')->cleanString($entity->label());

  $group_content_array = GroupContent::loadByEntity($entity);
  $group_content = reset($group_content_array);
  if ($group_content) {
    $group = $group_content->getGroup();
    $group_alias = $path_alias_manager->getAliasByPath('/group/' . $group->id());

    // Make sure group has a proper alias.
    if ($group_alias == '/group/' . $group->id()) {
      return;
    }

    $new_alias = $group_alias . '/' . $page_title;

    /** @var \Drupal\pathauto\AliasUniquifier $alias_uniquifier */
    $alias_uniquifier = \Drupal::service('pathauto.alias_uniquifier');
    $alias_uniquifier->uniquify($new_alias, $source, $langcode);

    if ($source !== $new_alias) {
      $path_alias = PathAlias::create([
        'path' => $source,
        'alias' => $new_alias,
      ]);

      $path_alias->save();
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function hr_paragraphs_group_content_insert(EntityInterface $entity) {
  /** @var \Drupal\group\Entity\GroupContent $entity */
  $plugin_id = $entity->getGroupContentType()->getContentPluginId();

  if ($plugin_id === 'group_node:page') {
    return hr_paragraphs_group_content_alias($entity);
  }

  if ($plugin_id === 'subgroup:cluster') {
    return hr_paragraphs_group_subgroup_alias($entity);
  }

  if ($plugin_id === 'group_membership') {
    return hr_paragraphs_group_add_member($entity);
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function hr_paragraphs_group_add_member(EntityInterface $entity) {
  /** @var \Drupal\group\Entity\GroupContent $entity */
  $group = $entity->getGroup();

  /** @var \Drupal\user\Entity\User $member */
  $member = $entity->getEntity();

  // Skip UID 0 and 1.
  if ($member->id() <= 1) {
    return;
  }

  \Drupal::logger('hr_members')->info('@member (@uid) added to @group (@gid)', [
    '@member' => $member->getAccountName(),
    '@uid' => $member->id(),
    '@group' => $group->label(),
    '@gid' => $group->id(),
  ]);

  if ($member->isBlocked()) {
    $member->activate();
    $member->save();

    \Drupal::logger('hr_members')->info('@member (@uid) account automatically unblocked', [
      '@member' => $member->getAccountName(),
      '@uid' => $member->id(),
    ]);
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function hr_paragraphs_group_subgroup_alias(EntityInterface $entity) {
  /** @var \Drupal\group\Entity\GroupContent $entity */
  $plugin_id = $entity->getGroupContentType()->getContentPluginId();
  if ($plugin_id != 'subgroup:cluster') {
    return;
  }

  $subgroup = $entity->getEntity();
  $group = $entity->getGroup();

  $path_alias_manager = \Drupal::service('path_alias.manager');

  $group_alias = $path_alias_manager->getAliasByPath('/group/' . $group->id());
  $page_title = \Drupal::service('pathauto.alias_cleaner')->cleanString($entity->label());
  $new_alias = $group_alias . '/' . $page_title;

  $langcode = LanguageInterface::LANGCODE_NOT_SPECIFIED;
  $source = '/group/' . $subgroup->id();

  /** @var \Drupal\pathauto\AliasUniquifier $alias_uniquifier */
  $alias_uniquifier = \Drupal::service('pathauto.alias_uniquifier');
  $alias_uniquifier->uniquify($new_alias, $source, $langcode);

  if ($source !== $new_alias) {
    $path_alias = PathAlias::create([
      'path' => $source,
      'alias' => $new_alias,
    ]);

    $path_alias->save();
  }

  // Add aliases for tabs.
  $tabs = [
    'events',
    'contacts',
    'pages',
    'reports',
    'maps',
    'data',
    'assessments',
  ];

  foreach ($tabs as $tab) {
    $source = '/group/' . $subgroup->id() . '/' . $tab;
    $tab_alias = $new_alias . '/' . $tab;

    $existing_alias = $path_alias_manager->getAliasByPath($source);

    // Skip if an alias is already set.
    if ($existing_alias !== $source) {
      continue;
    }

    if ($source !== $tab_alias) {
      $path_alias = PathAlias::create([
        'path' => $source,
        'alias' => $tab_alias,
      ]);

      $path_alias->save();
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function hr_paragraphs_group_content_alias(EntityInterface $entity) {
  /** @var \Drupal\group\Entity\GroupContent $entity */
  $plugin_id = $entity->getGroupContentType()->getContentPluginId();
  if ($plugin_id != 'group_node:page') {
    return;
  }

  $node = $entity->getEntity();
  $group = $entity->getGroup();

  $langcode = LanguageInterface::LANGCODE_NOT_SPECIFIED;
  $source = '/node/' . $node->id();

  $path_alias_manager = \Drupal::service('path_alias.manager');
  $node_alias = $path_alias_manager->getAliasByPath($source);

  // Skip if an alias is already set.
  if ($node_alias !== $source) {
    return;
  }

  $page_title = \Drupal::service('pathauto.alias_cleaner')->cleanString($node->label());

  $group_alias = $path_alias_manager->getAliasByPath('/group/' . $group->id());
  $new_alias = $group_alias . '/' . $page_title;

  /** @var \Drupal\pathauto\AliasUniquifier $alias_uniquifier */
  $alias_uniquifier = \Drupal::service('pathauto.alias_uniquifier');
  $alias_uniquifier->uniquify($new_alias, $source, $langcode);

  if ($source !== $new_alias) {
    $path_alias = PathAlias::create([
      'path' => $source,
      'alias' => $new_alias,
    ]);

    $path_alias->save();
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function hr_paragraphs_group_content_update(EntityInterface $entity) {
  return hr_paragraphs_group_content_insert($entity);
}

/**
 * Implements hook_preprocess_paragraph().
 */
function hr_paragraphs_preprocess_paragraph(&$variables) {
  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['paragraph'];

  $view_mode = $variables['view_mode'];
  if ($view_mode === 'preview') {

    // Check emptiness.
    $is_empty = TRUE;
    $outputted_fields = array_keys($variables['content']);

    foreach ($paragraph->getFields(FALSE) as $field) {
      if (in_array($field->getName(), $outputted_fields)) {
        if (!$field->isEmpty()) {
          $is_empty = FALSE;
        }
      }
    }

    if ($is_empty) {
      $variables['content']['empty_indicator'] = [
        '#type' => 'markup',
        '#markup' => t('No preview available'),
        '#weight' => -100,
        '#prefix' => '<div class="paragraph-empty-indicator">',
        '#suffix' => '</div>',
      ];
    }

    $variables['content']['indicator'] = [
      '#type' => 'markup',
      '#markup' => $paragraph->getParagraphType()->label(),
      '#weight' => -100,
      '#prefix' => '<div class="paragraph-preview-indicator">',
      '#suffix' => '</div>',
    ];
  }
}

/**
 * Implements hook_preprocess_paragraph__type().
 */
function hr_paragraphs_preprocess_paragraph__iframe(&$variables) {
  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['paragraph'];
  $embed_url = '';

  if (!$paragraph->field_iframe_url->isEmpty()) {
    $embed_url = $paragraph->get('field_iframe_url')->first()->uri;
    $width = '100%';
    $height = '500px';
  }
  elseif (!$paragraph->field_embed_code->isEmpty()) {
    $settings = hr_paragraphs_handle_iframe($paragraph->field_embed_code->value);
    $embed_url = $settings['embed_url'];
    $width = $settings['width'];
    $height = $settings['height'];
  }

  if (empty($embed_url)) {
    return;
  }

  if (!$paragraph->field_iframe_aspect_ratio->isEmpty()) {
    $ratio = $paragraph->field_iframe_aspect_ratio->value;
  }
  else {
    $ratio = 'ratio-16-9';
  }

  $variables['content']['embed'] = [
    '#theme' => 'hr_paragraphs_iframe',
    '#embed_url' => $embed_url,
    '#width' => $width,
    '#height' => $height,
    '#ratio' => $ratio,
    '#weight' => 99,
  ];
}

/**
 * Validate iframe code and wrap it.
 */
function hr_paragraphs_handle_iframe($html) {
  $flags = LIBXML_NONET | LIBXML_NOBLANKS | LIBXML_NOERROR | LIBXML_NOWARNING;
  $prefix = '<!DOCTYPE html><html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"></head><body>';
  $suffix = '</body></html>';
  $dom = new \DOMDocument();
  $dom->loadHTML($prefix . $html . $suffix, $flags);

  $iframes = $dom->getElementsByTagName('iframe');
  $iframe = $iframes[0];
  if (!$iframe) {
    return [
      'embed_url' => '',
      'width' => 0,
      'height' => 0,
    ];
  }

  return [
    'embed_url' => $iframe->getAttribute('src'),
    'width' => intval($iframe->getAttribute('width'), 10),
    'height' => intval($iframe->getAttribute('height'), 10),
  ];
}

/**
 * Implements hook_preprocess_paragraph__type().
 */
function hr_paragraphs_preprocess_paragraph__rss_feed(&$variables) {
  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['paragraph'];

  if ($paragraph->field_rss_link->isEmpty()) {
    return;
  }

  $rss_options = $paragraph->field_rss_options->getValue();
  foreach ($rss_options as &$rss_option) {
    $rss_option = $rss_option['value'];
  }

  $max_number_of_items = $paragraph->field_max_number_of_items->value ?? 5;
  $options = [
    'display_date' => FALSE,
    'display_description' => FALSE,
    'display_each_item_full' => FALSE,
    'display_read_more' => FALSE,
  ];

  /** @var \Drupal\hr_paragraphs\Controller\RssController $rss_controller */
  $rss_controller = \Drupal::service('hr_paragraphs.rss_controller');
  $items = $rss_controller->getRssItems($paragraph->field_rss_link->first()->uri);

  if (empty($items)) {
    return;
  }

  if (in_array('display_date', $rss_options)) {
    $options['display_date'] = TRUE;
  }

  // Slice array.
  $items = array_slice($items, 0, $max_number_of_items);

  $variables['content']['embed'] = [
    '#theme' => 'hr_paragraphs_rss_feed',
    '#items' => $items,
    '#options' => $options,
    '#weight' => 99,
    '#cache' => [
      'max-age' => 60 * 60,
    ],
  ];

  // Add 'read more' if needed.
  if (in_array('display_read_more', $rss_options)) {
    $read_more_url = '';

    if ($paragraph->field_rss_read_more->isEmpty()) {
      $channel_link = $rss_controller->getRssChannelLink($paragraph->field_rss_link->first()->uri);
      if (!empty($channel_link)) {
        $read_more_url = $channel_link;
        $options['display_read_more'] = TRUE;
      }
    }
    else {
      $read_more_url = $paragraph->field_rss_read_more->first()->uri;
      $options['display_read_more'] = TRUE;
    }

    if ($options['display_read_more']) {
      $variables['content']['embed']['#read_more'] = [
        'url' => $read_more_url,
      ];
    }
  }
}

/**
 * Implements hook_preprocess_paragraph__type().
 */
function hr_paragraphs_preprocess_paragraph__upcoming_events(&$variables) {
  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['paragraph'];
  $group = $paragraph->getParentEntity();

  if (!$group) {
    return;
  }

  if ($group->field_ical_url->isEmpty()) {
    return;
  }

  /** @var \Drupal\hr_paragraphs\Controller\IcalController $ical_controller */
  $ical_controller = \Drupal::service('hr_paragraphs.ical_controller');
  $start = date('Y-m-d');
  $end = date('Y-m-d', time() + 30 * 24 * 60 * 60);

  try {
    $events = $ical_controller->getIcalEvents($group, $start, $end);
  }
  catch (\Exception $exception) {
    // Fail silently.
    return [];
  }

  // Sort by start time.
  usort($events, function ($a, $b) {
    return strtotime($b['start']) < strtotime($a['start']) ? 1 : -1;
  });

  // Limit to 5 by default.
  $max_number_of_items = $paragraph->field_max_number_of_items->value ?? 5;

  // Slice array.
  $events = array_slice($events, 0, $max_number_of_items);

  $variables['content']['upcoming'] = [
    '#theme' => 'upcoming_events',
    '#events' => $events,
    '#read_more' => [
      'title' => 'More events',
      'url' => Url::fromRoute('hr_paragraphs.operation.events', [
        'group' => $group->id(),
      ]),
    ],
    '#weight' => 99,
    '#cache' => [
      'max-age' => 60 * 60,
    ],
  ];
}

/**
 * Implements hook_preprocess_paragraph__type().
 */
function hr_paragraphs_preprocess_paragraph__child_groups(&$variables) {
  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['paragraph'];

  /** @var \Drupal\group\Entity\Group */
  $group = $paragraph->getParentEntity();

  // For preview mode.
  if (!$group) {
    return;
  }

  // If we are on page, get the group.
  if (get_class($group) == 'Drupal\node\Entity\Node') {
    $group_content_array = GroupContent::loadByEntity($group);
    $group_content = reset($group_content_array);
    if ($group_content) {
      $group = $group_content->getGroup();
    }
    else {
      return;
    }
  }

  if (!$group) {
    return;
  }

  try {
    /** @var \Drupal\subgroup\Entity\SubgroupHandlerInterface $subgroup_handler */
    $subgroup_handler = \Drupal::entityTypeManager()->getHandler($group->getEntityTypeId(), 'subgroup');
    if (!$subgroup_handler->hasDescendants($group)) {
      return;
    }
    $children = $subgroup_handler->getDescendants($group);

    if (empty($children)) {
      return;
    }

    $items = [];
    $cache_tags = [];
    foreach ($children as $child) {
      $cache_tags += $child->getCacheTags();
      $items[] = [
        'label' => $child->label->value,
        'link' => Url::fromRoute('entity.group.canonical', [
          'group' => $child->id(),
        ]),
      ];
    }

    // Sort by label.
    $collator = new Collator('en_US');
    usort($items, function ($a, $b) use ($collator) {
      return $collator->compare($a['label'], $b['label']);
    });

    $variables['content']['children'] = [
      '#theme' => 'group_children',
      '#children' => $items,
      '#weight' => 99,
    ];

    $variables['#cache']['tags'] = array_merge($variables['#cache']['tags'] ?? [], $cache_tags);
    $variables['#cache']['contexts'] = [
      'languages',
    ];
  }
  catch (MalformedLeafException $exception) {
    return;
  }
}

/**
 * Implements hook_preprocess_paragraph__type().
 */
function hr_paragraphs_preprocess_paragraph__group_pages(&$variables) {
  $exclude_pages = [];

  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['paragraph'];

  /** @var \Drupal\group\Entity\Group $group */
  $group = $paragraph->getParentEntity();

  // For preview mode.
  if (!$group) {
    return;
  }

  // If we are on page, get the group.
  if (get_class($group) == 'Drupal\node\Entity\Node') {
    $exclude_pages[] = $group->id();
    $group_content_array = GroupContent::loadByEntity($group);
    $group_content = reset($group_content_array);
    if ($group_content) {
      $group = $group_content->getGroup();
    }
    else {
      return;
    }
  }

  $groups = [
    $group,
  ];

  // Include pages of subgroups.
  if ($paragraph->hasField('field_include_subgroups') && $paragraph->field_include_subgroups->value) {
    /** @var \Drupal\subgroup\Entity\SubgroupHandlerInterface $subgroup_handler */
    $subgroup_handler = \Drupal::entityTypeManager()->getHandler($group->getEntityTypeId(), 'subgroup');
    if (!$subgroup_handler->hasDescendants($group)) {
      return;
    }
    $groups = array_merge($groups, $subgroup_handler->getDescendants($group));
  }

  $nodes = [];
  foreach ($groups as $group) {
    // Exclude special pages.
    if ($group->hasField('field_offices_page') && !$group->field_offices_page->isEmpty()) {
      /** @var \Drupal\link\Plugin\Field\FieldType\LinkItem $link */
      $link = $group->field_offices_page->first();

      if (!$link->isExternal()) {
        try {
          $params = $link->getUrl()->getRouteParameters();
          $exclude_pages[] = $params['node'];
        }
        catch (\Exception $exception) {
          // Ignore, deleted page.
        }
      }
    }

    if ($group->hasField('field_pages_page') && !$group->field_pages_page->isEmpty()) {
      /** @var \Drupal\link\Plugin\Field\FieldType\LinkItem $link */
      $link = $group->field_pages_page->first();

      if (!$link->isExternal()) {
        try {
          $params = $link->getUrl()->getRouteParameters();
          $exclude_pages[] = $params['node'];
        }
        catch (\Exception $exception) {
          // Ignore, deleted page.
        }
      }
    }

    $nodes = array_merge($nodes, $group->getContentEntities('group_node:page'));
  }

  if (empty($nodes)) {
    return;
  }

  $items = [];
  $cache_tags = [];
  foreach ($nodes as $node) {
    // Skip current page.
    if (in_array($node->id(), $exclude_pages)) {
      continue;
    }

    $cache_tags += $node->getCacheTags();
    $items[] = [
      'label' => $node->title->value,
      'link' => Url::fromRoute('entity.node.canonical', [
        'node' => $node->id(),
      ]),
    ];
  }

  // Sort by label.
  $collator = new Collator('en_US');
  usort($items, function ($a, $b) use ($collator) {
    return $collator->compare($a['label'], $b['label']);
  });

  $variables['content']['nodes'] = [
    '#theme' => 'group_nodes',
    '#nodes' => $items,
    '#weight' => 99,
  ];

  $variables['#cache']['tags'] = array_merge($variables['#cache']['tags'] ?? [], $cache_tags);
}

/**
 * Implements hook_preprocess_paragraph__type().
 */
function hr_paragraphs_preprocess_paragraph__hdx_river(&$variables) {
  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['paragraph'];

  // Make sure link is set.
  if (!$paragraph->hasField('field_hdx_url') || $paragraph->field_hdx_url->isEmpty()) {
    return;
  }

  // Set max number of items to 5 by default.
  $max_number_of_items = $paragraph->field_max_number_of_items->value ?? 5;

  $url = $paragraph->field_hdx_url->first()->uri;
  /** @var \Drupal\hr_paragraphs\Controller\HdxController */
  $hdx_controller = \Drupal::service('hr_paragraphs.hdx_controller');
  $query_filters = $hdx_controller->parseHdxUrl($url);
  $parameters = $hdx_controller->buildHdxParameters(0, $max_number_of_items, $query_filters);
  $results = $hdx_controller->executeHdxQuery($parameters);

  $variables['content']['rw_list'] = [
    '#theme' => 'hr_paragraphs_rw_list',
    '#data' => $hdx_controller->buildHdxObjects($results),
    '#view_all' => $paragraph->field_hdx_url->first()->uri,
    '#total' => $max_number_of_items,
    '#weight' => 99,
    '#cache' => [
      'max-age' => 60 * 60,
    ],
  ];
}

/**
 * Implements hook_preprocess_paragraph__type().
 */
function hr_paragraphs_preprocess_paragraph__reliefweb_river(&$variables) {
  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['paragraph'];

  // Make sure link is set.
  if (!$paragraph->hasField('field_reliefweb_url') || $paragraph->field_reliefweb_url->isEmpty()) {
    return;
  }

  // Set max number of items to 5 by default.
  $max_number_of_items = $paragraph->field_max_number_of_items->value ?? 5;

  $url = $paragraph->field_reliefweb_url->first()->uri;
  /** @var \Drupal\hr_paragraphs\Controller\ReliefwebController */
  $reliefweb_controller = \Drupal::service('hr_paragraphs.reliefweb_controller');
  $conditions = $reliefweb_controller->parseReliefwebUrl($url);
  $parameters = $reliefweb_controller->buildReliefwebParameters(0, $max_number_of_items, []);

  // Remove facets.
  unset($parameters['facets']);

  // Check for search paramater as well.
  if (isset($conditions['_query'])) {
    $parameters['query'] = [
      'value' => $conditions['_query'],
      'operator' => 'AND',
    ];
    unset($conditions['_query']);
  }

  foreach ($conditions as $condition) {
    $negative_operators = [
      'and-without',
      'or-without',
    ];
    $negate = FALSE;

    if (in_array($condition['operator'], $negative_operators)) {
      $negate = TRUE;
    }

    $parameters['filter']['conditions'][] = [
      'field' => $condition['field'],
      'value' => $condition['value'],
      'negate' => $negate,
    ];
  }

  $results = $reliefweb_controller->executeReliefwebQuery($parameters);

  $variables['content']['rw_list'] = [
    '#theme' => 'hr_paragraphs_rw_list',
    '#data' => $reliefweb_controller->buildReliefwebObjects($results),
    '#view_all' => $paragraph->field_reliefweb_url->first()->uri,
    '#total' => $max_number_of_items,
    '#weight' => 99,
    '#cache' => [
      'max-age' => 60 * 60,
    ],
  ];
}

/**
 * Implements hook_preprocess_paragraph__type().
 */
function hr_paragraphs_preprocess_paragraph__reliefweb_document(&$variables) {
  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['paragraph'];

  // Make sure link is set.
  if (!$paragraph->hasField('field_reliefweb_url') || $paragraph->field_reliefweb_url->isEmpty()) {
    return;
  }

  $url = $paragraph->field_reliefweb_url->first()->uri;

  /** @var \Drupal\hr_paragraphs\Controller\ReliefwebController */
  $reliefweb_controller = \Drupal::service('hr_paragraphs.reliefweb_controller');
  $parameters = $reliefweb_controller->buildReliefwebParameters(0, 1, []);

  // Remove facets.
  unset($parameters['facets']);

  $parameters['filter']['conditions'][] = [
    'field' => 'url_alias',
    'value' => $url,
  ];

  $results = $reliefweb_controller->executeReliefwebQuery($parameters);

  // Try using canonical URL.
  if (!isset($results['data']) || empty($results['data'])) {
    $parameters = $reliefweb_controller->buildReliefwebParameters(0, 1, []);

    // Remove facets.
    unset($parameters['facets']);

    $parts = explode('/', $url);
    $id = array_pop($parts);

    $parameters['filter']['conditions'][] = [
      'field' => 'id',
      'value' => $id,
    ];

    try {
      $results = $reliefweb_controller->executeReliefwebQuery($parameters);
    }
    catch (\Exception $e) {
      $results = [];
    }
  }

  if (empty($results) || empty($results['data'])) {
    return;
  }

  $docs = $reliefweb_controller->buildReliefwebObjects($results);
  $doc = reset($docs);

  $variables['content']['rw_list'] = [
    '#theme' => 'hr_paragraphs_rw_list',
    '#data' => [$doc],
    '#total' => NULL,
    '#view_all' => NULL,
    '#weight' => 99,
    '#cache' => [
      'max-age' => 60 * 60,
    ],
  ];
}

/**
 * Implements hook_preprocess_paragraph__type().
 */
function hr_paragraphs_preprocess_paragraph__reliefweb_key_figures(&$variables) {
  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['paragraph'];

  // Make sure Country is set.
  if (!$paragraph->hasField('field_country') || $paragraph->field_country->isEmpty()) {
    return;
  }

  // Fetch country from user input.
  $key_figures_country = $paragraph->field_country->value;

  // Fetch label of the user input.
  $key_figures_country_labels = $paragraph->getFieldDefinition('field_country')->getFieldStorageDefinition()->getSetting('allowed_values');

  // Set max number of items to 4 by default.
  $max_number_of_items = $paragraph->field_max_number_of_items->value ?? 4;

  /** @var \Drupal\hr_paragraphs\Controller\KeyFiguresController */
  $key_figures_controller = \Drupal::service('hr_paragraphs.key_figures_controller');
  $results = $key_figures_controller->getKeyFigures($key_figures_country);

  $variables['content']['key_figures'] = [
    '#theme' => 'hr_paragraphs_rw_key_figures',
    '#country_iso' => $key_figures_country,
    '#country_name' => $key_figures_country_labels[$key_figures_country],
    '#data' => $key_figures_controller->buildKeyFigures($results, $max_number_of_items),
    '#weight' => 99,
    '#cache' => [
      'max-age' => 12 * 60 * 60,
    ],
  ];
}

/**
 * Validate date filter values.
 *
 * @param string $code
 *   Filter code.
 * @param array $values
 *   Filter values.
 *
 * @return array
 *   Dates with a 'from' or a 'to' key or both.
 */
function hr_paragraphs_validate_date_filter_values($code, array $values) {
  if (empty($values)) {
    return [];
  }
  // We only accept one range.
  $values = $values[0];

  $values = array_map(function ($value) {
    if (strlen($value) !== 8 || !ctype_digit($value)) {
      return NULL;
    }
    $date = date_create_immutable_from_format('Ymd|', $value, timezone_open('UTC'));
    return $date;
  }, explode('-', $values, 2));

  $dates = [];
  if (count($values) === 1) {
    if (!empty($values[0])) {
      $dates['from'] = $values[0];
      $dates['to'] = $values[0];
    }
  }
  else {
    // If the to date is before the from date, we inverse the dates.
    if (!empty($values[0]) && !empty($values[1]) && $values[1] < $values[0]) {
      $temp = $values[0];
      $values[0] = $values[1];
      $values[1] = $temp;
    }

    if (!empty($values[0])) {
      $dates['from'] = $values[0];
    }
    if (!empty($values[1])) {
      $dates['to'] = $values[1];
    }
  }

  return $dates;
}

/**
 * Implements hook_library_info_alter().
 */
function hr_paragraphs_library_info_alter(&$libraries, $extension) {
  if ($extension !== 'fullcalendar_api') {
    return;
  }

  $new_file = '/' . drupal_get_path('module', 'hr_paragraphs') . '/component/events/js/fullcalendar.js';
  $replacements = [
    'js/fullcalendar.load.js' => $new_file,
  ];

  $new_js = [];
  foreach ($libraries['fullcalendar_load']['js'] as $source => $options) {
    if (isset($replacements[$source])) {
      $new_js[$replacements[$source]] = $options;
    }
    else {
      $new_js[$source] = $options;
    }
  }
  $libraries['fullcalendar_load']['js'] = $new_js;
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function hr_paragraphs_menu_local_tasks_alter(&$data, $route_name) {
  if (empty($data['tabs'])) {
    return;
  }

  $weights = [
    'hr_paragraphs.operation' => -10,
    'group.view' => 0,
    'group.edit_form' => 5,
    'group.delete_form' => 10,
    'group.version_history' => 15,
    'views_view:view.group_members.page_1' => 20,
    'views_view:view.subgroups_of_a_group.page_1' => 30,
    'views_view:view.group_nodes.page_1' => 40,
    'content_translation.local_tasks:entity.group.content_translation_overview' => 100,
    'hr_paragraphs.operation.operations' => 999,
    'group.content' => 999,
  ];

  // Pages is pages.
  if (isset($data['tabs'][0]['views_view:view.group_nodes.page_1'])) {
    $data['tabs'][0]['views_view:view.group_nodes.page_1']['#link']['title'] = t('Pages');
  }

  // Re-order tabs.
  foreach ($data['tabs'][0] as $key => &$tab) {
    if (isset($weights[$key])) {
      $tab['#weight'] = $weights[$key];
    }
  }

  // Hide add existing content local task.
  if (isset($data['tabs'][0]['group.view']['#access'])) {
    $data['tabs'][0]['group.view']['#access'] = FALSE;
  }

  // Hide duplicate local task.
  if (isset($data['tabs'][0]['group.view']['#access'])) {
    $data['tabs'][0]['group.view']['#access'] = FALSE;
  }

  // Hide all entities.
  if (isset($data['tabs'][0]['group.content']['#access'])) {
    $data['tabs'][0]['group.content']['#access'] = FALSE;
  }

  // Mark local task active for queries.
  $supported_routes = [
    'hr_paragraphs.operation.pages',
    'hr_paragraphs.operation.reports',
    'hr_paragraphs.operation.maps',
    'hr_paragraphs.operation.assessments',
    'hr_paragraphs.operation.data',
    'hr_paragraphs.operation.events',
    'hr_paragraphs.operation.contacts',
    'hr_paragraphs.operation.ical',
  ];

  if (in_array($route_name, $supported_routes)) {
    if ($data['tabs'][1][$route_name]['#active']) {
      if (!isset($data['tabs'][1][$route_name]['#link']['localized_options']['attributes']['class'])) {
        $data['tabs'][1][$route_name]['#link']['localized_options']['attributes']['class'] = [];
      }

      $data['tabs'][1][$route_name]['#link']['localized_options']['attributes']['class'][] = 'is-active';
    }
  }

  // Mark link as being external if needed.
  $group = \Drupal::routeMatch()->getParameter('group');
  if ($group) {
    foreach ($supported_routes as $tab_name) {
      if (!isset($data['tabs'][1][$tab_name])) {
        continue;
      }

      if (!isset($data['tabs'][1][$tab_name]['#link']['localized_options']['attributes']['class'])) {
        $data['tabs'][1][$tab_name]['#link']['localized_options']['attributes']['class'] = [];
      }

      switch ($tab_name) {
        case 'hr_paragraphs.operation.reports':
          if ($group->hasField('field_documents_page') && !$group->field_documents_page->isEmpty()) {
            $data['tabs'][1][$tab_name]['#link']['localized_options']['attributes']['class'][] = 'is-external';
            $data['tabs'][1][$tab_name]['#link']['localized_options']['attributes']['target'] = '_blank';
          }
          break;

        case 'hr_paragraphs.operation.maps':
          if ($group->hasField('field_infographics') && !$group->field_infographics->isEmpty()) {
            $data['tabs'][1][$tab_name]['#link']['localized_options']['attributes']['class'][] = 'is-external';
            $data['tabs'][1][$tab_name]['#link']['localized_options']['attributes']['target'] = '_blank';
          }
          break;

        case 'hr_paragraphs.operation.assessments':
          if ($group->hasField('field_assessments_page') && !$group->field_assessments_page->isEmpty()) {
            $data['tabs'][1][$tab_name]['#link']['localized_options']['attributes']['class'][] = 'is-external';
            $data['tabs'][1][$tab_name]['#link']['localized_options']['attributes']['target'] = '_blank';
          }
          break;

        case 'hr_paragraphs.operation.data':
          if ($group->hasField('field_hdx_alternate_source') && !$group->field_hdx_alternate_source->isEmpty()) {
            $data['tabs'][1][$tab_name]['#link']['localized_options']['attributes']['class'][] = 'is-external';
            $data['tabs'][1][$tab_name]['#link']['localized_options']['attributes']['target'] = '_blank';
          }
          break;

        case 'hr_paragraphs.operation.events':
          if ($group->hasField('field_calendar_alternate_link') && !$group->field_calendar_alternate_link->isEmpty()) {
            $data['tabs'][1][$tab_name]['#link']['localized_options']['attributes']['class'][] = 'is-external';
            $data['tabs'][1][$tab_name]['#link']['localized_options']['attributes']['target'] = '_blank';
          }
          break;

        case 'hr_paragraphs.operation.contacts':
          if ($group->hasField('field_offices_page') && !$group->field_offices_page->isEmpty()) {
            /** @var \Drupal\link\Plugin\Field\FieldType\LinkItem $link */
            $link = $group->field_offices_page->first();
            if ($link->isExternal()) {
              $data['tabs'][1][$tab_name]['#link']['localized_options']['attributes']['class'][] = 'is-external';
              $data['tabs'][1][$tab_name]['#link']['localized_options']['attributes']['target'] = '_blank';
            }
          }

          break;

      }
    }
  }
}

/**
 * Implements hook_system_breadcrumb_alter().
 */
function hr_paragraphs_system_breadcrumb_alter(Breadcrumb &$breadcrumb, RouteMatchInterface $route_match, array $context) {
  if (empty($breadcrumb)) {
    return;
  }

  if ($route_match->getRouteName() !== 'entity.group.add_form') {
    return;
  }

  $links = $breadcrumb->getLinks();
  if (!empty($links[1])) {
    $title = \Drupal::service('title_resolver')->getTitle(\Drupal::request(), $route_match->getRouteObject());
    $links[1]->setText($title);
    $breadcrumb = new Breadcrumb();
    $breadcrumb->setLinks($links);
  }
}

/**
 * Implements hook_menu_local_actions_alter().
 */
function hr_paragraphs_menu_local_actions_alter(&$local_actions) {
  if (isset($local_actions['group.add_group'])) {
    unset($local_actions['group.add_group']);
  }

  if (isset($local_actions['group_content.group_node_relate_page'])) {
    unset($local_actions['group_content.group_node_relate_page']);
  }

  if (isset($local_actions['group_content.group_node_add_page'])) {
    $local_actions['group_content.group_node_add_page']['title'] = t('Add new page');
  }
}

/**
 * Implements hook_preprocess_node().
 */
function hr_paragraphs_preprocess_node(&$variables) {
  hr_paragraphs_node_sidebar($variables);
  hr_paragraphs_node_is_archived($variables);
  hr_paragraphs_user_can_edit($variables);
}

/**
 * Implements hook_preprocess_node().
 */
function hr_paragraphs_user_can_edit(&$variables) {
  /** @var \Drupal\node\NodeInterface $node */
  $node = $variables['node'];

  /** @var \Drupal\user\Entity\User $current_user */
  $current_user = \Drupal::currentUser();

  $variables['can_edit'] = FALSE;
  if ($node->access('update', $current_user)) {
    $variables['can_edit'] = TRUE;
    return;
  }
}

/**
 * Implements hook_preprocess_node().
 */
function hr_paragraphs_node_sidebar(&$variables) {
  if ($variables['view_mode'] != 'full') {
    return;
  }

  /** @var \Drupal\node\NodeInterface $node */
  $node = $variables['node'];

  // Page without sidebar.
  if ($node->hasField('field_hide_sidebar') && !$node->field_hide_sidebar->isEmpty() && $node->field_hide_sidebar->value) {
    return;
  }

  $group_content_array = GroupContent::loadByEntity($node);
  $group_content = reset($group_content_array);
  if ($group_content) {
    $group = $group_content->getGroup();

    if ($group->hasField('field_sidebar_from_operation') && !$group->field_sidebar_from_operation->isEmpty() && $group->field_sidebar_from_operation->value) {
      if ($group->hasField('subgroup_tree') && !$group->subgroup_tree->isEmpty()) {
        $group = Group::load($group->subgroup_tree->value);
      }
    }

    if ($group->hasField('field_sidebar_menu') && !$group->field_sidebar_menu->isEmpty()) {
      $variables['field_sidebar_menu'] = $group->field_sidebar_menu->view();
    }
  }
}

/**
 * Implements hook_preprocess_node().
 */
function hr_paragraphs_node_is_archived(&$variables) {
  $node = $variables['node'];

  if (!($node instanceof Node)) {
    return;
  }

  $variables['is_archived'] = FALSE;
  /** @var \Drupal\group\Entity\Storage\GroupContentStorage */
  $storage = \Drupal::entityTypeManager()->getStorage('group_content');
  $activGroupListEntity = $storage->loadByEntity($node);

  // Not a group node.
  if (empty($activGroupListEntity)) {
    return;
  }

  foreach ($activGroupListEntity as $groupContent) {
    $group = $groupContent->getGroup();
    if (!$group->hasField('field_archive_group')) {
      continue;
    }

    // Allow it if part of at least 1 non-archived group.
    if (!$group->field_archive_group->value) {
      // Check parent.
      if ($group->hasField('subgroup_tree') && !$group->subgroup_tree->isEmpty()) {
        $group = Group::load($group->subgroup_tree->value);
        if ($group->hasField('field_archive_group') && !$group->field_archive_group->value) {
          return;
        }
      }
      else {
        return;
      }
    }
  }

  $variables['is_archived'] = TRUE;
  $variables['archive_message'] = t('This group has been archived.');
  if (!$group->field_archive_message->isEmpty()) {
    $variables['archive_message'] = $group->field_archive_message->value;
  }
}

/**
 * Implements hook_preprocess_group().
 */
function hr_paragraphs_preprocess_group(&$variables) {
  hr_paragraphs_group_sidebar($variables);
  hr_paragraphs_group_is_archived($variables);
}

/**
 * Implements hook_preprocess_group().
 */
function hr_paragraphs_group_sidebar(&$variables) {
  if ($variables['view_mode'] != 'full') {
    return;
  }

  /** @var \Drupal\group\Entity\GroupInterface $group */
  $group = $variables['elements']['#group'];

  if ($group->hasField('field_sidebar_from_operation') && !$group->field_sidebar_from_operation->isEmpty() && $group->field_sidebar_from_operation->value) {
    if ($group->hasField('subgroup_tree') && !$group->subgroup_tree->isEmpty()) {
      $group = Group::load($group->subgroup_tree->value);
      if ($group->hasField('field_sidebar_menu') && !$group->field_sidebar_menu->isEmpty()) {
        $variables['content']['field_sidebar_menu'] = $group->field_sidebar_menu->view();
      }
    }
  }
}

/**
 * Implements hook_preprocess_group().
 */
function hr_paragraphs_group_is_archived(&$variables) {
  /** @var \Drupal\group\Entity\GroupInterface $group */
  $group = $variables['elements']['#group'] ?? $variables['group'];

  if (!$group) {
    return;
  }

  if (!$group->hasField('field_archive_group')) {
    return;
  }

  $variables['is_archived'] = FALSE;
  if (!$group->field_archive_group->value) {
    // Check parent.
    if ($group->hasField('subgroup_tree') && !$group->subgroup_tree->isEmpty()) {
      $group = Group::load($group->subgroup_tree->value);
      if ($group->hasField('field_archive_group') && !$group->field_archive_group->value) {
        return;
      }
    }
    else {
      return;
    }
  }

  $variables['is_archived'] = TRUE;
  $variables['archive_message'] = t('This group has been archived.');
  if (!$group->field_archive_message->isEmpty()) {
    $variables['archive_message'] = $group->field_archive_message->value;
  }
}

/**
 * Parse query string, allowing duplicate keys.
 */
function hr_paragraphs_parse_str($string) {
  $results = [];
  $parts = explode('&', $string);

  foreach ($parts as $part) {
    if (strpos($part, '=') === FALSE) {
      continue;
    }

    // Split into name and value.
    [$name, $value] = explode('=', $part, 2);

    // Decode value.
    $value = urldecode($value);

    // If name already exists.
    if (isset($results[$name])) {
      // Stick multiple values into an array.
      if (is_array($results[$name])) {
        $results[$name][] = $value;
      }
      else {
        $results[$name] = [$results[$name], $value];
      }
    }
    // Otherwise, simply stick it in a scalar.
    else {
      $results[$name] = $value;
    }
  }

  return $results;
}

/**
 * Implements template_preprocess_html().
 */
function hr_paragraphs_preprocess_html(&$variables) {
  /** @var Drupal\group\Entity\Group $group */
  $group = \Drupal::request()->attributes->get('group');
  if (!$group) {
    return;
  }

  /** @var \Drupal\Core\Routing\RouteMatch $route_match */
  $route_match = \Drupal::routeMatch();
  if (!$route_match) {
    return;
  }

  // Only act on group homepage and tabs.
  if (strpos($route_match->getRouteName(), 'hr_paragraphs.operation.') === FALSE && strpos($route_match->getRouteName(), 'entity.group.canonical') === FALSE) {
    return;
  }

  // Add operation name for cluster homepage.
  if (strpos($route_match->getRouteName(), 'entity.group.canonical') !== FALSE) {
    if ($group->bundle() == 'cluster' && $group->hasField('subgroup_tree') && !$group->subgroup_tree->isEmpty()) {
      $operation = Group::load($group->subgroup_tree->value);
      $variables['head_title']['title'] = $operation->label->value . ': ' . $variables['head_title']['title'];
    }

    return;
  }

  if ($group->bundle() == 'cluster' && $group->hasField('subgroup_tree') && !$group->subgroup_tree->isEmpty()) {
    $operation = Group::load($group->subgroup_tree->value);
    $variables['head_title']['title'] = $operation->label->value . ': ' . $group->label->value . ' - ' . $variables['head_title']['title'];
  }
  else {
    $variables['head_title']['title'] = $group->label->value . ' - ' . $variables['head_title']['title'];
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function hr_paragraphs_theme_registry_alter(&$theme_registry) {
  if (!isset($theme_registry['fullcalendar_calendar'])) {
    return;
  }

  $theme_registry['fullcalendar_calendar']['variables']['group'] = NULL;
}

/**
 * Implements hook_preprocess_river().
 */
function hr_paragraphs_preprocess_river(&$variables) {
  hr_paragraphs_group_is_archived($variables);
}

/**
 * Implements hook_preprocess_fullcalendar_calendar().
 */
function hr_paragraphs_preprocess_fullcalendar_calendar(&$variables) {
  hr_paragraphs_group_is_archived($variables);
}

/**
 * Implements hook_ENTITY_TYPE_create_access().
 *
 * @see subgroup_group_create_access()
 */
function hr_paragraphs_group_create_access(AccountInterface $account, array $context, $entity_bundle) {
  /** @var \Drupal\group\Entity\GroupInterface $entity */
  $group_type = \Drupal::entityTypeManager()->getStorage('group_type')->load($entity_bundle);

  return AccessResult::neutral()->addCacheableDependency($group_type);
}

/**
 * Implements hook_module_implements_alter().
 *
 * @see hr_paragraphs_group_create_access()
 */
function hr_paragraphs_module_implements_alter(array &$implementations, string $hook) {
  if ($hook !== 'group_create_access') {
    return;
  }

  if (isset($implementations['subgroup'])) {
    unset($implementations['subgroup']);
  }
}

/**
 * Implements hook_form_alter().
 */
function hr_paragraphs_form_alter(&$form, $form_state, $form_id) {
  $form_ids = [
    'group_content_operation-group_membership_add_form',
    'group_content_operation-group_membership_edit_form',
    'group_content_cluster-group_membership_add_form',
    'group_content_cluster-group_membership_edit_form',
  ];

  if (in_array($form_id, $form_ids)) {
    if (isset($form['path'])) {
      unset($form['path']);
    }
  }
}

/**
 * Implements template_preprocess_views_view().
 */
function hr_paragraphs_preprocess_views_view(&$variables) {
  /** @var \Drupal\views\Entity\View */
  $view = $variables['view'];
  if ($view->id() == 'group_members' && $view->current_display == 'page_1') {
    if (!isset($view->args[0])) {
      return;
    }

    // Load the group.
    $group_id = $view->args[0];
    $group = Group::load($group_id);
    if ($group->bundle() == 'operation') {
      return;
    }

    // Get operation.
    if (!$group->hasField('subgroup_tree') || $group->subgroup_tree->isEmpty()) {
      return;
    }

    $parent = Group::load($group->subgroup_tree->value);
    $url = Url::fromRoute('view.group_members.page_1', [
      'group' => $parent->id(),
    ]);
    $operation_manager = TRUE;

    // Make sure user has access.
    $userCurrent = \Drupal::currentUser();
    if (!$url->access($userCurrent)) {
      $url = Url::fromRoute('entity.group.canonical', [
        'group' => $parent->id(),
      ]);
      $operation_manager = FALSE;

      if (!$url->access($userCurrent)) {
        return;
      }
    }

    $variables['cluster_message'] = [
      'operation_manager' => $operation_manager,
      'operation' => $parent->label(),
      'link' => $url->toString(),
    ];
  }
}

/**
 * Implements hook_group_content_info_alter().
 */
function hr_paragraphs_group_content_info_alter(&$definitions) {
  // Allow blocked users to be added to a group.
  $definitions['group_membership']['class'] = 'Drupal\hr_paragraphs\Plugin\GroupContentEnabler\AllGroupMembership';
  $definitions['group_membership']['provider'] = 'hr_paragraphs';
}

/**
 * Remove any layout paragraph.
 */
function hr_paragraphs_remove_layout_paragraph_from_node($id) {
  hr_paragraphs_remove_layout_paragraph_from_entity('node', $id);
}

/**
 * Remove any layout paragraph.
 */
function hr_paragraphs_remove_layout_paragraph_from_group($id) {
  hr_paragraphs_remove_layout_paragraph_from_entity('group', $id);
}

/**
 * Remove any layout paragraph.
 */
function hr_paragraphs_remove_layout_paragraph_from_entity($entity_type, $id) {
  $storage = \Drupal::entityTypeManager()->getStorage($entity_type);
  $entity = $storage->load($id);

  if (!$entity) {
    return;
  }

  if (!$entity->hasField('field_paragraphs')) {
    return;
  }

  $paras = $entity->field_paragraphs->referencedEntities();
  foreach ($paras as $delta => $para) {
    if ($para->bundle() == 'layout') {
      unset($paras[$delta]);
    }
    else {
      $para->setAllBehaviorSettings([
        'layout_paragraphs' => [
          'parent_uuid' => NULL,
          'region' => NULL,
        ],
      ]);
      $para->save();
    }
  }

  $entity->field_paragraphs = $paras;
  $entity->save();
}

/**
 * Implements hook_mail().
 */
function hr_paragraphs_mail($key, &$message, $params) {
  switch ($key) {
    case 'user_created':
      $message['subject'] = t('New HID login on Response site');
      $message['body'][] = t("Dear team\n\nThere is new user created on the site.");
      $message['body'][] = t("\n\nEmail address: @mail.", [
        '@mail' => $params['mail'],
      ]);
      break;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function hr_paragraphs_form_views_exposed_form_alter(&$form, $form_state, $form_id) {
  if ($form['#id'] === 'views-exposed-form-groups-page-1' || $form['#id'] === 'views-exposed-form-subgroups-of-a-group-page-1') {
    $form['status']['#options'][1] = t('Published');
    $form['status']['#options'][0] = t('Unpublished');

    $form['archived']['#options'][1] = t('Yes');
    $form['archived']['#options'][0] = t('No');
  }
  elseif ($form['#id'] === 'views-exposed-form-content-page-1') {
    // Load all groups.
    $groups = Group::loadMultiple();

    // Build options.
    foreach ($groups as $group) {
      $value = $group->label();

      if ($group->hasField('subgroup_tree') && !$group->subgroup_tree->isEmpty()) {
        if ($group->id() != $group->subgroup_tree->value) {
          $parent = Group::load($group->subgroup_tree->value);
          $value = $parent->label() . ' > ' . $value;
        }
      }

      if (!empty($value)) {
        $options[$group->id()] = $value;
      }
    }

    // Sort and add an All option.
    asort($options);
    $options = ['' => 'All'] + $options;

    // Output as select list.
    if (isset($form['gid'])) {
      $form['gid']['#type'] = 'select';
      $form['gid']['#options'] = $options;
      $form['gid']['#size'] = 1;

    }
  }
}
