sync_domain: 'http://hrinfo.docksal.site'
sync_credentials: ''
csv_source_dir: /var/www/tsv/
notification_new_user_enabled: false
reliefweb_api_endpoint: 'https://api.reliefweb.int/v2/reports'
reliefweb_api_appname: response
