_core:
  default_config_hash: NFnOZU6VCOfURCAR4-O3V7eMHTx2LNqnCmDKRSNjjns
always_save_userinfo: true
connect_existing_users: false
override_registration_settings: false
end_session_enabled: true
user_login_display: hidden
redirect_login: ''
redirect_logout: /
userinfo_mappings:
  timezone: zoneinfo
  user_picture: picture
role_mappings: {  }
