<?php

/**
 * @file
 * OCHA Document store connector.
 */

use Drupal\Core\Form\FormStateInterface;
use Solarium\Core\Query\QueryInterface  as SolariumQueryInterface;
use Drupal\search_api\Query\QueryInterface as SearchApiQueryInterface;

/**
 * Alter base url of the endpoints.
 */
function ocha_docstore_files_get_endpoint_base($endpoint) {
  $base_url = \Drupal::config('ocha_docstore_files.settings')->get('endpoint_url');

  if (empty($base_url)) {
    return $endpoint;
  }

  $path = parse_url($endpoint, PHP_URL_PATH);
  return rtrim($base_url, '/') . $path;
}

/**
 * Alter api-key of the endpoints.
 */
function ocha_docstore_files_get_endpoint_apikey($apikey) {
  $endpoint_apikey = \Drupal::config('ocha_docstore_files.settings')->get('endpoint_apikey');

  if (empty($endpoint_apikey)) {
    return $apikey;
  }

  return $endpoint_apikey;
}

/**
 * Implements hook_inline_entity_form_entity_form_alter().
 *
 * Ensure external entities created via an inline entity form are saved.
 */
function ocha_docstore_files_inline_entity_form_entity_form_alter(array &$entity_form, FormStateInterface &$form_state) {
  if (isset($entity_form['#entity']) && is_a($entity_form['#entity'], '\Drupal\external_entities\Entity\ExternalEntity')) {
    $entity_form['#save_entity'] = TRUE;
  }

  if (isset($entity_form['field_author'])) {
    if (empty($entity_form['field_author']['widget'][0]['value']['#default_value'])) {
      /** @var Drupal\Core\Session\AccountProxy $account */
      $account = \Drupal::currentUser();

      $entity_form['field_author']['widget'][0]['value']['#default_value'] = $account->getDisplayName();
    }

    $entity_form['field_author']['widget'][0]['value']['#attributes']['readonly'] = TRUE;
    $entity_form['field_author']['widget'][0]['value']['#attributes']['disabled'] = TRUE;
    $entity_form['title']['widget'][0]['value']['#title'] = t('Internal label');
  }
}

/**
 * Implements hook_entity_type_alter().
 */
function ocha_docstore_files_entity_type_alter(array &$entity_types) {
  if (!empty($entity_types['external_entity_type'])) {
    $external_entity_type_config = $entity_types['external_entity_type'];

    // Get the existing external entity type configurations.
    $external_entity_types = \Drupal::entityTypeManager()->createHandlerInstance(
      $external_entity_type_config->getHandlerClass('storage'),
      $external_entity_type_config
    )->loadMultiple();

    foreach ($external_entity_types as $external_entity_type) {
      $entity_types[$external_entity_type->id()]->setHandlerClass('access', 'Drupal\ocha_docstore_files\OchaExternalEntityAccessControlHandler');
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ocha_docstore_files_form_assessment_edit_form_alter(&$form, $form_state, $form_id) {
  if (isset($form['field_author'])) {
    /** @var Drupal\Core\Session\AccountProxy $account */
    $account = \Drupal::currentUser();

    if ($form['field_author']['widget'][0]['value']['#default_value'] === 'AR') {
      $form['field_author']['widget'][0]['value']['#default_value'] = $account->getDisplayName();
    }

    if (!$account->hasPermission('ocha docstore files edit author')) {
      $form['field_author']['widget'][0]['value']['#attributes']['readonly'] = TRUE;
      $form['field_author']['widget'][0]['value']['#attributes']['disabled'] = TRUE;
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ocha_docstore_files_form_assessment_form_alter(&$form, $form_state, $form_id) {
  if (isset($form['field_author'])) {
    /** @var Drupal\Core\Session\AccountProxy $account */
    $account = \Drupal::currentUser();

    if (empty($form['field_author']['widget'][0]['value']['#default_value']) || $form['field_author']['widget'][0]['value']['#default_value'] === 'AR') {
      $form['field_author']['widget'][0]['value']['#default_value'] = $account->getDisplayName();
    }

    if (!$account->hasPermission('ocha docstore files edit author')) {
      $form['field_author']['widget'][0]['value']['#attributes']['readonly'] = TRUE;
      $form['field_author']['widget'][0]['value']['#attributes']['disabled'] = TRUE;
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ocha_docstore_files_form_km_edit_form_alter(&$form, $form_state, $form_id) {
  if (isset($form['field_author'])) {
    /** @var Drupal\Core\Session\AccountProxy $account */
    $account = \Drupal::currentUser();

    if ($form['field_author']['widget'][0]['value']['#default_value'] === 'AR') {
      $form['field_author']['widget'][0]['value']['#default_value'] = $account->getDisplayName();
    }

    if (!$account->hasPermission('ocha docstore files edit author')) {
      $form['field_author']['widget'][0]['value']['#attributes']['readonly'] = TRUE;
      $form['field_author']['widget'][0]['value']['#attributes']['disabled'] = TRUE;
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ocha_docstore_files_form_km_form_alter(&$form, $form_state, $form_id) {
  if (isset($form['field_author'])) {
    /** @var Drupal\Core\Session\AccountProxy $account */
    $account = \Drupal::currentUser();

    if (empty($form['field_author']['widget'][0]['value']['#default_value']) || $form['field_author']['widget'][0]['value']['#default_value'] === 'AR') {
      $form['field_author']['widget'][0]['value']['#default_value'] = $account->getDisplayName();
    }

    if (!$account->hasPermission('ocha docstore files edit author')) {
      $form['field_author']['widget'][0]['value']['#attributes']['readonly'] = TRUE;
      $form['field_author']['widget'][0]['value']['#attributes']['disabled'] = TRUE;
    }
  }
}

/**
 * Implements hook_search_api_solr_query_alter().
 *
 * Tell Solr to return the stored entities.
 */
function ocha_docstore_files_search_api_solr_query_alter(SolariumQueryInterface $solarium_query, SearchApiQueryInterface $query) {
  // Get the mapping field names -> Solr field names.
  $solr_field_names = $query->getIndex()
    ->getServerInstance()
    ->getBackend()
    ->getSolrFieldNames($query->getIndex());

  // Tell solr to return the stored entity.
  if (!empty($solr_field_names['_stored_entity'])) {
    $solarium_query->addField($solr_field_names['_stored_entity']);
  }

  // Tell solr to return the stored country.
  if (!empty($solr_field_names['_stored_country'])) {
    $solarium_query->addField($solr_field_names['_stored_country']);
  }
}

/**
 * Implements hook_facets_search_api_query_type_mapping_alter().
 *
 * Make our string query type available.
 */
function ocha_docstore_files_facets_search_api_query_type_mapping_alter($backend_plugin_id, array &$query_types) {
  $query_types['ar_string'] = 'ar_search_api_string';
}
